export const newProducts = [
    {
        id: 1,
        imgSrc: "https://www.diamantesa.es/wp-content/uploads/anillo-compromiso-diamantesa.png",
        imgHover: "https://img.edenly.com/pt/40/saturno-n11__2315317_1.png",
        category: "Novedades" ,
        productName: "Anillo de Compromiso",
        productPrice : "123",   
        quantity: 1,
    },
    {
        id: 2,
        imgSrc: "https://www.pngarts.com/files/3/Jewellery-PNG-Image.png",
        category: "Novedades" ,
        productName: "Collar de diamantes",
        productPrice : "120",   
        quantity: 1,
    },
    {
        id: 3,
        imgSrc: "https://www.klamore.com.mx/cdn/shop/products/aretes-sigrid-con-rubi-klamore-1_large.png?v=1661359655",
        category: "Novedades" ,
        productName: "Aretes de Ruby",
        productPrice : "45",
        quantity: 1,   
    },
    {
        id: 4,
        imgSrc: "https://png.pngtree.com/png-vector/20231223/ourmid/pngtree-white-gold-engagement-rings-with-diamonds-jewellery-png-image_10951588.png",
        category: "Novedades" ,
        productName: "Anillo de Compromiso",
        productPrice : "35", 
        quantity: 1,  
    },
    {
        id: 5,
        imgSrc: "https://static.vecteezy.com/system/resources/previews/011/356/618/original/pair-of-gold-wedding-rings-png.png",
        category: "Novedades" ,
        productName: "Anillo de Oro",
        productPrice : "56", 
        quantity: 1,  
    },
    {
        id: 6,
        imgSrc: "https://www.pngarts.com/files/3/Jewellery-PNG-Transparent-Image.png",
        category: "Novedades" ,
        productName: "Collar de Perlas",
        productPrice : "78", 
        quantity: 1,  
    },
    {
        id: 7,
        imgSrc: "https://www.freeiconspng.com/thumbs/jewellery-png/green-jewellery-png-1.png",
        category: "Novedades" ,
        productName: "Collar de Jade",
        productPrice : "90", 
        quantity: 1,  
    },
    {
        id: 8,
        imgSrc: "https://purepng.com/public/uploads/large/purepng.com-diamond-ringclothingdiamond-ringfashion-jewelry-ring-stone-love-wedding-object-gold-accessory-diamond-jewel-marriage-relationship-wed-marry-jewellery-631522327134cylgt.png",
        category: "Novedades" ,
        productName: "Anillo de Diamante",
        productPrice : "300", 
        quantity: 1,  
    },
    {
        id: 9,
        imgSrc: "https://www.candere.com/media/jewellery/images/C022504__1.png",
        category: "Novedades" ,
        productName: "Dije de Flor",
        productPrice : "78", 
        quantity: 1,  
    },
    {
        id: 10,
        imgSrc: "https://precedenceinternational.com/wp-content/uploads/2022/02/diamond-jewellery.png",
        category: "Novedades" ,
        productName: "Anillos de Diamantes",
        productPrice : "500",
        quantity: 1,
    },
];

export const releaseProducts = [
    {
        id: 11,
        imgSrc: "https://pngimg.es/d/ring_PNG75.png",
        category: "Lanzamientos" ,
        productName: "Anillo de Diamante",
        productPrice : "500",   
        quantity: 1,
    },
    {
        id: 12,
        imgSrc: "https://i.pinimg.com/originals/aa/ba/ea/aabaea54fa4eeec02000d35c552e3fd6.png",
        category: "Lanzamientos" ,
        productName: "Aretes de Ruby",
        productPrice : "120",   
        quantity: 1,
    },
    {
        id: 13,
        imgSrc: "https://pngimg.com/d/jewelry_PNG6809.png",
        category: "Lanzamientos" ,
        productName: "Aretes de Plata",
        productPrice : "45",
        quantity: 1,   
    },
    {
        id: 14,
        imgSrc: "https://freepngimg.com/thumb/jewelry/13-diamond-earrings-png-image.png",
        category: "Lanzamientos" ,
        productName: "Anillo de Zafiro",
        productPrice : "35", 
        quantity: 1,  
    },
    {
        id: 15,
        imgSrc: "https://pngimg.com/d/necklace_PNG43.png",
        category: "Lanzamientos" ,
        productName: "Collar de Oro Blanco",
        productPrice : "56", 
        quantity: 1,  
    },
    {
        id: 16,
        imgSrc: "https://laperlajoyeriasonline.com/cdn/shop/products/ARETES_1.png?v=1530314114",
        category: "Lanzamientos" ,
        productName: "Anillo de Perlas",
        productPrice : "150",   
        quantity: 1,
    },
    {
        id: 17,
        imgSrc: "https://png.pngtree.com/png-clipart/20221003/original/pngtree-diamons-drop-earrings-png-image_8653852.png",
        category: "Lanzamientos" ,
        productName: "Aretes de Zafiro y Diamantes",
        productPrice : "120",   
        quantity: 1,
    },
    {
        id: 18,
        imgSrc: "https://berger.com.mx/wp-content/uploads/2021/08/47914E-1.png",
        category: "Lanzamientos" ,
        productName: "Aretes de Diamante rosa",
        productPrice : "450",
        quantity: 1,   
    },
    {
        id: 19,
        imgSrc: "https://www.pngmart.com/files/6/Earring-PNG-Photos.png",
        category: "Lanzamientos" ,
        productName: "Arete de Oro Blanco",
        productPrice : "200", 
        quantity: 1,  
    },
    {
        id: 20,
        imgSrc: "https://static.vecteezy.com/system/resources/thumbnails/009/788/611/small/earrings-watercolor-illustration-free-png.png",
        category: "Lanzamientos" ,
        productName: "Arete",
        productPrice : "56", 
        quantity: 1,  
    },
];
export const clothesProducts = [
    {
        id: 21,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5445.png",
        category: "Ropa" ,
        productName: "Playera Blanca",
        productPrice : "150",
        quantity: 1,
    },
    {
        id: 22,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5447.png",
        category: "Ropa" ,
        productName: "Playera licra blanca",
        productPrice : "200",
        quantity: 1,
    },
    {
        id: 23,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5446.png",
        category: "Ropa" ,
        productName: "Playera Negra",
        productPrice : "180",
        quantity: 1,
    },
    {
        id: 24,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5448.png",
        category: "Ropa" ,
        productName: "Playera Gris",
        productPrice : "190",
        quantity: 1,
    },
    {
        id: 25,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5449.png",
        category: "Ropa" ,
        productName: "Playera Roja",
        productPrice : "170",
        quantity: 1,
    },
    {
        id: 26,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png",
        category: "Ropa" ,
        productName: "Playera Azul",
        productPrice : "160",
        quantity: 1,
    },
    {
        id: 27,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5451.png",
        category: "Ropa" ,
        productName: "Playera Negra",
        productPrice : "140",
        quantity: 1,
    },
    {
        id: 28,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5452.png",
        category: "Ropa" ,
        productName: "Playera Blanca",
        productPrice : "130",
        quantity: 1,
    },
    {
        id: 29,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5453.png",
        category: "Ropa" ,
        productName: "Playera Rosa",
        productPrice : "120",
        quantity: 1,
    },
    {
        id: 30,
        imgSrc: "https://pngimg.com/uploads/tshirt/tshirt_PNG5454.png",
        category: "Ropa" ,
        productName: "Playera Verde",
        productPrice : "110",
        quantity: 1,
    }
];
export const necklaceProducts = [
    {
        id: 31,
        imgSrc: "https://eurostore.melaniemartinezmusic.com/on/demandware.static/-/Sites-warner-master/default/dw15b356c9/pdp-img-eu/Melanie%20Martinez/October%202023%20Merch/Portals%20Necklace.png",
        category: "Collares" ,
        productName: "Collar de Mariposa",
        productPrice : "123",
        quantity: 1,
    },
    {
        id: 32,
        imgSrc: "https://pngimg.com/d/necklace_PNG90.png",
        category: "Collares" ,
        productName: "Collar de diamantes",
        productPrice : "120",
        quantity: 1,
    },
    {
        id: 33,
        imgSrc: "https://www.pngmart.com/files/22/Necklace-PNG-Free-Download.png",
        category: "Collares" ,
        productName: "Collar de Plata",
        productPrice : "45",
        quantity: 1,
    },
    {
        id: 34,
        imgSrc: "https://www.pngmart.com/files/22/Necklace-PNG-Image.png",
        category: "Collares" ,
        productName: "Collar de Oro",
        productPrice : "35",
        quantity: 1,
    },
    {
        id: 35,
        imgSrc: "https://pngimg.com/d/necklace_PNG44.png",
        category: "Collares" ,
        productName: "Collar de Diamantes",
        productPrice : "56",
        quantity: 1,
    },
    {
        id: 36,
        imgSrc: "https://pngimg.com/d/necklace_PNG92.png",
        category: "Collares" ,
        productName: "Collar de Perlas",
        productPrice : "78",
        quantity: 1,
    },
    {
        id: 37,
        imgSrc: "https://www.pngmart.com/files/22/Necklace-PNG-Photos.png",
        category: "Collares" ,
        productName: "Collar de Corazón",
        productPrice : "90",
        quantity: 1,
    },
    {
        id: 38,
        imgSrc: "https://www.pngmart.com/files/22/Necklace-PNG-File.png",
        category: "Collares" ,
        productName: "Collar de Estrella",
        productPrice : "100",
        quantity: 1,
    },
    {
        id: 39,
        imgSrc: "https://www.pngmart.com/files/22/Necklace-PNG-Image.png",
        category: "Collares" ,
        productName: "Collar de Luna",
        productPrice : "110",
        quantity: 1,
    },
    {
        id: 40,
        imgSrc: "https://d2z62bbv9zdnvg.cloudfront.net/app-source/product-images/mehar-heart-pendant-22012018181043-main.png?q=30&w=104&h=104",
        category: "Collares" ,
        productName: "Collar de Corazón",
        productPrice : "120",
        quantity: 1,
    },
]

